name: 'Integration tests'
on: [push, workflow_call]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DEBUG: false
          envkey_SOME_API_KEY: "api_key"
          envkey_ACCESS_TOKEN_SECRET: r7hv0yjd9XiqKx47s43ViMoCgSAD1I4z8EupUw/msUPUyvBr56Xhs9NfNU/Nx7Zq
          envkey_REFRESH_TOKEN_SECRET: senha
          envkey_POSTGRES_USER: root
          envkey_POSTGRES_PASSWORD: passwordfordb
          envkey_POSTGRES_DB: main
          envkey_DATABASE_URL: postgresql://root:passwordfordb@database/main
          envkey_REDIS_PASSWORD: passforredis
          envkey_REDIS_HOST: cache
          envkey_REDIS_PORT: 6379
          file_name: ".env.test.local"
          fail_on_empty: false
          directory: .
      - name: Make env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DEBUG: false
          envkey_SOME_API_KEY: "api_key"
          envkey_DATABASE_URL: postgresql://root:passwordfordb@0.0.0.0:5432/main
          file_name: ".env"
          fail_on_empty: false
      - name: 'Run services'
        run: docker compose --env-file .env.test.local up -d database cache
      - name: Generate lock file
        run: npm i --package-lock-only
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install deps
        run: npm i
      - name: 'Sync database with schema'
        run: npx prisma db push
      - name: 'Run integration tests'
        run: docker compose --env-file .env.test.local up integration_tests --exit-code-from integration_tests
