name: 'Integration tests'
on: [push, workflow_call]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DEBUG: false
          envkey_SOME_API_KEY: "api_key"
          envkey_ACCESS_TOKEN_SECRET: r7hv0yjd9XiqKx47s43ViMoCgSAD1I4z8EupUw/msUPUyvBr56Xhs9NfNU/Nx7Zq
          envkey_REFRESH_TOKEN_SECRET: senha
          envkey_POSTGRES_USER: root
          envkey_POSTGRES_PASSWORD: eY8nPg78828BNTSY
          envkey_POSTGRES_DB: main
          envkey_DATABASE_URL: "postgresql://root:eY8nPg78828BNTSY@testing-database/main?schema=public"
          envkey_REDIS_PASSWORD: C7YY3nxBYHek2g5s
          envkey_REDIS_URL: "redis://:C7YY3nxBYHek2g5s@cache"
          envkey_MQ_URL: "amqp://guest:guest@message-queue"
          envkey_SMTP_PROVIDER: "smtp.ethereal.email"
          envkey_SMTP_PORT: 587
          envkey_SMTP_USER: "johathan.miller77@ethereal.email"
          envkey_SMTP_PASSWORD: "EUKwwjbS5Qax2ZJDBt"
          file_name: ".env.test.ci"
          fail_on_empty: false
          directory: .
      - name: 'Run integration tests'
        run: docker compose --env-file .env.test.ci up integration_tests --exit-code-from integration_tests
